# Generated by Django 5.2 on 2026-03-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='items_per_page',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='low_stock_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rental_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
