# Generated by Django 5.2 on 2025-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcategory',
            name='image',
            field=models.CharField(blank=True, help_text='URL for the rental category card image (displayed on Rent page)', max_length=255, null=True),
        ),
    ]
