# Generated by Django 5.2 on 2025-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        # Add the missing columns
        migrations.AddField(
            model_name='restorationgallery',
            name='before_image',
            field=models.CharField(default='', max_length=255, help_text="URL for the 'before restoration' image"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restorationgallery',
            name='after_image',
            field=models.CharField(default='', max_length=255, help_text="URL for the 'after restoration' image"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restorationgallery',
            name='make',
            field=models.CharField(blank=True, max_length=100, help_text="Make of the scooter (e.g., Vespa, Honda)"),
        ),
        migrations.AddField(
            model_name='restorationgallery',
            name='date_completed',
            field=models.DateField(blank=True, null=True, help_text="Date when the restoration was completed"),
        ),
    ]
