# Generated by Django 5.2 on 2025-06-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rentalcategory_alter_brand_logo_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_1',
            field=models.CharField(blank=True, help_text='URL for the first thumbnail image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_2',
            field=models.CharField(blank=True, help_text='URL for the second thumbnail image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_3',
            field=models.CharField(blank=True, help_text='URL for the third thumbnail image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_4',
            field=models.CharField(blank=True, help_text='URL for the fourth thumbnail image', max_length=255, null=True),
        ),
    ]
