# Generated by Django 5.2 on 2025-07-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20250714_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the homepage video', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description for the video')),
                ('video_url', models.URLField(help_text='URL of the video (e.g., YouTube embed link, direct video link)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this video is currently active on the homepage')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Video',
                'verbose_name_plural': 'Homepage Videos',
                'ordering': ['-date_added'],
            },
        ),
    ]
