# Generated by Django 5.2 on 2026-03-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_rentalcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_location', models.CharField(choices=[('rent_hero', 'Rent Page – Hero Image'), ('restore_hero', 'Restore Page – Hero Image'), ('service_hero', 'Service Page – Hero Image')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='site_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Image',
                'verbose_name_plural': 'Site Images',
            },
        ),
    ]
