# Generated by Django 5.2 on 2025-07-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_homepagevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagevideo',
            options={'verbose_name': 'Homepage Video', 'verbose_name_plural': 'Homepage Videos'},
        ),
        migrations.RenameField(
            model_name='homepagevideo',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='homepagevideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='homepagevideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='homepagevideo',
            name='video_file',
            field=models.FileField(default='videos/default.mp4', help_text='Upload video file (MP4 format recommended)', upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagevideo',
            name='description',
            field=models.TextField(help_text='Short description for the video'),
        ),
    ]
