# Generated by Django 5.2 on 2025-06-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_jobcard_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='service_type',
            field=models.CharField(choices=[('service', 'Service'), ('repair', 'Repair'), ('quote', 'Quote'), ('breakdown', 'Breakdown')], default='service', help_text='Type of service being performed', max_length=20),
        ),
    ]
