# Generated by Django 5.2 on 2025-07-02 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_jobcard_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount in currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total before VAT and discount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT amount in currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
