# Generated by Django 5.2 on 2025-06-26 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchase_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='part',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='quantity',
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.parts')),
                ('stock_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='inventory.stocktransfer')),
            ],
            options={
                'unique_together': {('stock_transfer', 'part')},
            },
        ),
    ]
