# Generated by Django 5.2 on 2026-03-07 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_purchase_discount_amount_purchase_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost in currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
